### PR TITLE
Use post.excerpt as summary and add DISGUS support

### PR DESCRIPTION
**Pull request by finfin**
For better SEO and more flexibility
Changed to use [Post excerpts](http://jekyllrb.com/docs/posts/#post-excerpts) in the **description meta-tag**
Index.html also use post exceprt as post summary
So users can customize excerpt on front matter and it will be reflected on index and SEO

Also add a new config parameter: **disgus**
site with this parameter will try to load and display disgus at the end of post

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Why are you calling it disgus while it's called disqus? Is this on purpose?

**Comment by finfin** [comment]
sorry it was definitely a typo, fixed

**Comment by lucianosousa** [comment]
Thanks man!
Put disqus config on my website and works! ;)

**Comment by usbsnowcrash** [comment]
:+1:

**Pull request merged**
